name: flutter_build_environment
description: An example project about build environment separate in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_package_name_icon:
    git: git://github.com/devibrahimkarahan/flutter_package_name_icon.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dursun/
    - assets/temel/

